In [55]:
import pandas as pd
import numpy as np

## Set up to print every columns and rows
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', None)

#### Input txt file
Two files are made by using playground.py and KITplayground.py file in analysis/ directory.   
First line contains like this:

    evtID    ele_pt    ele_phi ...... pho_phi    ID


Contents are like this:

    12140472    77.13    2.92  ...... 232.0    2.500    4

In [109]:
# txt files includes numbers from ntuples
#  evtID ele_pt ele_phi ...
file1 = 'sort_KIT_checkID.txt'
file2 = 'sort_COFFEA_checkID.txt'
f1 = 'KIT'
f2 = 'KNU'

In [110]:
## Read two files and save df1, df2
df1 = pd.read_csv(file1, sep='\s+')
df2 = pd.read_csv(file2, sep='\s+')

In [111]:
## Merge two data frame on event ID 'evtID'
merged_df = pd.merge(df1, df2, on='evtID', suffixes=('_KIT','_KNU'))
merged_df

          evtID  METpt_KIT  METphi_KIT  ele_pt_KIT  ele_phi_KIT  ele_eta_KIT  pho_pt_KIT  pho_phi_KIT  pho_eta_KIT  mu_pt_KIT  mu_phi_KIT  recoil_KIT  METpt_KNU  METphi_KNU  ele_pt_KNU  ele_phi_KNU  ele_eta_KNU  ele_ID  pho_pt_KNU  pho_phi_KNU  pho_eta_KNU  pho_ID  mu_pt_KNU  mu_phi_KNU  recoil_KNU
0      12140472      77.13        2.92         NaN          NaN          NaN       232.0      2.50000     -0.83900        NaN         NaN      304.37      77.11        2.92         NaN          NaN          NaN     NaN       232.0      2.50000     -0.83900     3.0        NaN         NaN      304.00
1      12329882     113.92        0.09       220.0      0.24500      0.34500        22.5      0.44700     -0.96300        NaN         NaN      333.02     113.95        0.09       220.0      0.24500      0.34500     4.0        22.5      0.44700     -0.96300     1.0        NaN         NaN      333.00
2      12493384     227.40       -1.10       277.0     -0.99000     -2.18000         NaN          NaN          NaN        NaN         NaN      503.60     227.47       -1.10       277.0     -0.99000     -2.18000     3.0         NaN          NaN          NaN     NaN        NaN         NaN      504.00
3      12886623      30.43       -1.65         NaN          NaN          NaN       290.0     -0.53800     -0.88600        NaN         NaN      304.69      30.44       -1.66         NaN          NaN          NaN     NaN       290.0     -0.53800     -0.88600     3.0        NaN         NaN      305.00
4      13234955     108.11        2.46        80.4     -0.57600     -0.35700         NaN          NaN          NaN        NaN         NaN       29.42     108.13        2.46        80.4     -0.57600     -0.35700     4.0         NaN          NaN          NaN     NaN        NaN         NaN       29.40
5      13355477      24.20       -1.19         NaN          NaN          NaN       288.0     -1.41000      0.17900        NaN         NaN      311.86      24.19       -1.19         NaN          NaN          NaN     NaN       288.0     -1.41000      0.17900     3.0        NaN         NaN      312.00
6      14024648      98.70        2.11        98.7     -1.66000     -0.44000         NaN          NaN          NaN        NaN         NaN       61.40      98.78        2.11        98.7     -1.66000     -0.44000     4.0         NaN          NaN          NaN     NaN        NaN         NaN       61.60
7      14166655     106.63       -0.44        65.9      2.08000     -1.57000         NaN          NaN          NaN        NaN         NaN       65.45      96.67       -0.36        65.9      2.08000     -1.57000     4.0         NaN          NaN          NaN     NaN        NaN         NaN       62.60
8      14257086      18.80        2.29       312.0      0.73600      1.60000         NaN          NaN          NaN        NaN         NaN      312.33      18.80        2.29       312.0      0.73600      1.60000     2.0         NaN          NaN          NaN     NaN        NaN         NaN      312.00
9      14500098     195.73       -1.09       112.0     -1.15000     -2.15000         NaN          NaN          NaN        NaN         NaN      308.04     195.76       -1.09       112.0     -1.15000     -2.15000     4.0         NaN          NaN          NaN     NaN        NaN         NaN      308.00
10     14574036      44.62       -0.05         NaN          NaN          NaN       430.0      0.66300     -1.27000        NaN         NaN      464.69      44.63       -0.05         NaN          NaN          NaN     NaN       430.0      0.66300     -1.27000     3.0        NaN         NaN      465.00
11     14817158      38.57       -1.33       280.0     -1.25000     -2.31000         NaN          NaN          NaN        NaN         NaN      318.96      38.56       -1.33       280.0     -1.25000     -2.31000     4.0         NaN          NaN          NaN     NaN        NaN         NaN      319.00
12     15058156       9.04        0.50         NaN          NaN          NaN       354.0      1.97000      1.13000        NaN         NaN      355.18       9.03        0.49         NaN          NaN          NaN     NaN       354.0      1.97000      1.13000     3.0        NaN         NaN      355.00
13     15109513       5.56        1.90       267.0      2.65000      1.57000         NaN          NaN          NaN        NaN         NaN      271.36       5.57        1.90       267.0      2.65000      1.57000     4.0         NaN          NaN          NaN     NaN        NaN         NaN      271.00
14     15275530     185.45       -1.18       108.0     -1.17000     -2.18000         NaN          NaN          NaN        NaN         NaN      293.58     185.43       -1.18       108.0     -1.17000     -2.18000     2.0         NaN          NaN          NaN     NaN        NaN         NaN      294.00
15     15334175      85.46        1.09       272.0      1.55000      1.86000         NaN          NaN          NaN        NaN         NaN      350.22      85.49        1.09       272.0      1.55000      1.86000     2.0         NaN          NaN          NaN     NaN        NaN         NaN      350.00
16     15349320       8.29        0.93       303.0     -1.12000     -2.21000         NaN          NaN          NaN        NaN         NaN      299.52       8.28        0.93       303.0     -1.12000     -2.21000     2.0         NaN          NaN          NaN     NaN        NaN         NaN      300.00
17     15819992     148.29       -1.13       223.0     -1.37000     -1.91000         NaN          NaN          NaN        NaN         NaN      368.27     148.31       -1.13       223.0     -1.37000     -1.91000     2.0         NaN          NaN          NaN     NaN        NaN         NaN      368.00
18     15851771      32.36        1.95       354.0      0.19500     -0.19800         NaN          NaN          NaN        NaN         NaN      349.54      32.36        1.96       354.0      0.19500     -0.19800     2.0         NaN          NaN          NaN     NaN        NaN         NaN      350.00
19     16478456     137.55       -1.35        84.6      1.80000      1.66000         NaN          NaN          NaN        NaN         NaN       52.96     137.61       -1.35        84.6      1.80000      1.66000     4.0         NaN          NaN          NaN     NaN        NaN         NaN       53.00
20     16591904     169.81        2.54        94.4      0.68400     -0.92400         NaN          NaN          NaN        NaN         NaN      169.10     169.87        2.54        94.4      0.68400     -0.92400     4.0         NaN          NaN          NaN     NaN        NaN         NaN      169.00
21     17199910     106.75       -1.31       216.0     -1.23000     -2.01000         NaN          NaN          NaN        NaN         NaN      322.43     106.74       -1.31       216.0     -1.23000     -2.01000     3.0         NaN          NaN          NaN     NaN        NaN         NaN      322.00
22     17403506      73.63       -0.42       447.0      2.75000      0.89200         NaN          NaN          NaN        NaN         NaN      373.75      73.61       -0.42       447.0      2.75000      0.89200     2.0         NaN          NaN          NaN     NaN        NaN         NaN      374.00
23     17543206     148.65       -1.40       168.0     -1.48000     -2.13000         NaN          NaN          NaN        NaN         NaN      316.61     148.62       -1.40       168.0     -1.48000     -2.13000     2.0         NaN          NaN          NaN     NaN        NaN         NaN      317.00
24     17650964      34.62       -0.81         NaN          NaN          NaN       287.0     -0.47600     -1.10000        NaN         NaN      319.73      34.65       -0.81         NaN          NaN          NaN     NaN       287.0     -0.47600     -1.10000     3.0        NaN         NaN      320.00
25     17685670     238.01        1.97        81.6      2.12000     -0.26900         NaN          NaN          NaN        NaN         NaN      318.89     238.02        1.97        81.6      2.12000     -0.26900     4.0         NaN          NaN          NaN     NaN        NaN         NaN      319.00
26     17775708      49.55        1.25       260.0      0.79200      1.85000         NaN          NaN          NaN        NaN         NaN      305.35      49.55        1.25       260.0      0.79200      1.85000     2.0         NaN          NaN          NaN     NaN        NaN         NaN      305.00
27     17942969      30.73       -1.10         NaN          NaN          NaN       464.0     -1.47000      1.15000        NaN         NaN      492.70      30.74       -1.09         NaN          NaN          NaN     NaN       464.0     -1.47000      1.15000     3.0        NaN         NaN      493.00
28     18019668      22.69        2.47       456.0     -1.10000      1.06000         NaN          NaN          NaN        NaN         NaN      435.56      22.72        2.47       456.0     -1.10000      1.06000     4.0         NaN          NaN          NaN     NaN        NaN         NaN      436.00
29     18268325     275.53        2.63        19.6      2.51000      1.71000         NaN          NaN          NaN        NaN         NaN      295.04     275.60        2.63        19.6      2.51000      1.71000     4.0         NaN          NaN          NaN     NaN        NaN         NaN      295.00
30     18332910     118.44        0.65       502.0      0.64900     -0.57800         NaN          NaN          NaN        NaN         NaN      620.16     118.46        0.65       502.0      0.64900     -0.57800     4.0         NaN          NaN          NaN     NaN        NaN         NaN      620.00
31     18479093     122.24       -0.27       124.0     -3.00000     -1.28000         NaN          NaN          NaN        NaN         NaN       50.64     122.25       -0.27       124.0     -3.00000     -1.28000     4.0         NaN          NaN          NaN     NaN        NaN         NaN       50.60
32     18851318      61.58        0.75         NaN          NaN          NaN       295.0     -0.77400      1.18000        NaN         NaN      304.25      61.56        0.76         NaN          NaN          NaN     NaN       295.0     -0.77400      1.18000     3.0        NaN         NaN      304.00
33     18871895      17.27       -0.32       284.0     -0.84500     -2.17000         NaN          NaN          NaN        NaN         NaN      298.78      17.26       -0.32       284.0     -0.84500     -2.17000     2.0         NaN          NaN          NaN     NaN        NaN         NaN      299.00
34     18973582      97.97        2.95        76.2     -0.86600      0.25300         NaN          NaN          NaN        NaN         NaN       61.56      97.97        2.96        76.2     -0.86600      0.25300     4.0         NaN          NaN          NaN     NaN        NaN         NaN       61.60
35     19286141     105.62       -1.99       270.0      1.90000     -0.12600         NaN          NaN          NaN        NaN         NaN      206.01     105.64       -2.00       270.0      1.90000     -0.12600     4.0         NaN          NaN          NaN     NaN        NaN         NaN      206.00
36     19508071     103.34       -1.26        87.2      0.99300      1.21000         NaN          NaN          NaN        NaN         NaN       83.04     112.10       -1.35        87.2      0.99300      1.21000     4.0         NaN          NaN          NaN     NaN        NaN         NaN       80.50
37     19692271     101.05        1.08        75.2     -1.43000     -1.90000         NaN          NaN          NaN        NaN         NaN       60.52     101.10        1.08        75.2     -1.43000     -1.90000     4.0         NaN          NaN          NaN     NaN        NaN         NaN       60.50
38     19975212      26.07       -1.22         NaN          NaN          NaN       309.0     -1.00000     -1.19000        NaN         NaN      334.94      26.07       -1.22         NaN          NaN          NaN     NaN       309.0     -1.00000     -1.19000     3.0        NaN         NaN      335.00
39     20234075      70.73       -0.03         NaN          NaN          NaN       368.0     -2.82000     -1.16000        NaN         NaN      302.68      70.73       -0.03         NaN          NaN          NaN     NaN       368.0     -2.82000     -1.16000     3.0        NaN         NaN      303.00
40     20372777     198.00       -1.17       136.0     -1.16000     -2.12000         NaN          NaN          NaN        NaN         NaN      334.00     198.02       -1.17       136.0     -1.16000     -2.12000     4.0         NaN          NaN          NaN     NaN        NaN         NaN      334.00
41     20487331     134.71       -1.11       341.0     -1.09000     -1.97000         NaN          NaN          NaN        NaN         NaN      475.31     134.72       -1.11       341.0     -1.09000     -1.97000     3.0         NaN          NaN          NaN     NaN        NaN         NaN      475.00
42     20696240     157.70        3.14       194.0     -2.62000     -0.30600         NaN          NaN          NaN        NaN         NaN      339.97     157.67        3.14       194.0     -2.62000     -0.30600     3.0         NaN          NaN          NaN     NaN        NaN         NaN      340.00
43     20807837      68.27        2.78       240.0      2.34000     -0.95400         NaN          NaN          NaN        NaN         NaN      303.00      68.27        2.78       240.0      2.34000     -0.95400     4.0         NaN          NaN          NaN     NaN        NaN         NaN      303.00
44     21060825      74.79       -0.73       234.0     -1.44000     -2.03000         NaN          NaN          NaN        NaN         NaN      294.65      74.80       -0.73       234.0     -1.44000     -2.03000     4.0         NaN          NaN          NaN     NaN        NaN         NaN      295.00
45     21116395      62.99        0.57         NaN          NaN          NaN       346.0     -1.96000     -0.39200        NaN         NaN      296.52      63.03        0.57         NaN          NaN          NaN     NaN       346.0     -1.96000     -0.39200     3.0        NaN         NaN      296.00
46     30357588      33.40        0.58       651.0      0.42000      0.72900         NaN          NaN          NaN        NaN         NaN      684.36      33.41        0.58       651.0      0.42000      0.72900     2.0         NaN          NaN          NaN     NaN        NaN         NaN      684.00
47     33033318      34.87       -0.85         NaN          NaN          NaN       360.0      1.60000      0.63000        NaN         NaN      333.60      34.87       -0.85         NaN          NaN          NaN     NaN       360.0      1.60000      0.63000     3.0        NaN         NaN      334.00
48     37036957     141.50       -0.16        53.8      2.95000     -1.13000         NaN          NaN          NaN        NaN         NaN       87.72     141.47       -0.16        53.8      2.95000     -1.13000     4.0         NaN          NaN          NaN     NaN        NaN         NaN       87.70
49     37437757     170.76       -1.29       188.0     -1.28000     -1.91000         NaN          NaN          NaN        NaN         NaN      358.37     170.78       -1.29       188.0     -1.28000     -1.91000     2.0         NaN          NaN          NaN     NaN        NaN         NaN      358.00
50     37494153     104.15        2.50       107.0      0.72000     -0.30200         NaN          NaN          NaN        NaN         NaN      132.70     104.22        2.50       107.0      0.72000     -0.30200     4.0         NaN          NaN          NaN     NaN        NaN         NaN      133.00
51     37513252     102.19       -2.27       274.0     -2.38000      0.73200         NaN          NaN          NaN        NaN         NaN      375.67     102.21       -2.27       274.0     -2.38000      0.73200     2.0         NaN          NaN          NaN     NaN        NaN         NaN      376.00
52     37552657      34.96        2.29         NaN          NaN          NaN       304.0     -1.83000      0.84800        NaN         NaN      286.23      34.95        2.29         NaN          NaN          NaN     NaN       304.0     -1.83000      0.84800     3.0        NaN         NaN      286.00
53     37659467      43.08       -2.80         NaN          NaN          NaN       250.0     -2.92000     -0.09380        NaN         NaN      292.88      43.11       -2.80         NaN          NaN          NaN     NaN       250.0     -2.92000     -0.09380     3.0        NaN         NaN      293.00
54     37675345     102.90       -1.02       331.0     -1.12000     -2.19000         NaN          NaN          NaN        NaN         NaN      433.71     102.93       -1.02       331.0     -1.12000     -2.19000     4.0         NaN          NaN          NaN     NaN        NaN         NaN      434.00
55     37824846      36.59       -3.03         NaN          NaN          NaN       387.0     -1.14000      1.10000        NaN         NaN      377.51      36.64       -3.03         NaN          NaN          NaN     NaN       387.0     -1.14000      1.10000     3.0        NaN         NaN      377.00
56     37937260      59.06       -0.67       268.0     -1.08000     -1.82000         NaN          NaN          NaN        NaN         NaN      322.75      59.10       -0.67       268.0     -1.08000     -1.82000     3.0         NaN          NaN          NaN     NaN        NaN         NaN      323.00
57     38180754      93.66        2.59       243.0      2.17000     -2.19000         NaN          NaN          NaN        NaN         NaN      330.46      93.67        2.59       243.0      2.17000     -2.19000     4.0         NaN          NaN          NaN     NaN        NaN         NaN      330.00
58     38405239      24.02       -0.17         NaN          NaN          NaN       330.0     -2.77000     -1.23000        NaN         NaN      310.10      24.01       -0.17         NaN          NaN          NaN     NaN       330.0     -2.77000     -1.23000     2.0        NaN         NaN      310.00
59     38430353      28.73       -0.38       334.0     -1.18000      1.76000         NaN          NaN          NaN        NaN         NaN      354.82      28.73       -0.38         NaN          NaN          NaN     NaN       330.0     -1.17000      1.76000     3.0        NaN         NaN      351.00
60     38430977      23.75       -0.77         NaN          NaN          NaN       261.0     -2.02000     -0.02260        NaN         NaN      269.61      23.82       -0.76         NaN          NaN          NaN     NaN       261.0     -2.02000     -0.02260     3.0        NaN         NaN      270.00
61     38567013     306.39       -2.78        53.9      3.08000      0.54800         NaN          NaN          NaN        NaN         NaN      356.32     306.40       -2.78        53.9      3.08000      0.54800     4.0         NaN          NaN          NaN     NaN        NaN         NaN      356.00
62     38665009      13.81        3.11         NaN          NaN          NaN       390.0     -0.55900     -1.32000        NaN         NaN      377.74      13.84        3.11         NaN          NaN          NaN     NaN       390.0     -0.55900     -1.32000     3.0        NaN         NaN      378.00
63     38775816     112.70       -0.88        72.2      1.14000     -0.48500         NaN          NaN          NaN        NaN         NaN      103.90     112.72       -0.88        72.2      1.14000     -0.48500     4.0         NaN          NaN          NaN     NaN        NaN         NaN      104.00
64     38849177      36.14        0.09         NaN          NaN          NaN       267.0     -2.11000     -0.96500        NaN         NaN      247.05      36.12        0.09         NaN          NaN          NaN     NaN       267.0     -2.11000     -0.96500     3.0        NaN         NaN      247.00

In [116]:
## Compare Electron
column_name = 'ele_pt'
column_name2 = 'ele_eta'
column_name3 = 'ele_phi'
column_name4 = 'ele_ID'
different_values = merged_df[merged_df[f'{column_name}_{f1}'] != merged_df[f'{column_name}_{f2}']]
condition_e = different_values[[f'{column_name}_{f1}', f'{column_name}_{f2}']].isna().all(axis=1)
df_ele = different_values[~condition_e]
df_ele[['evtID', f'{column_name}_{f1}', f'{column_name}_{f2}',f'{column_name2}_{f1}',f'{column_name2}_{f2}',f'{column_name3}_{f1}',f'{column_name3}_{f2}',f'{column_name4}']]

         evtID  ele_pt_KIT  ele_pt_KNU  ele_eta_KIT  ele_eta_KNU  ele_phi_KIT  ele_phi_KNU  ele_ID
59    38430353       334.0         NaN         1.76          NaN     -1.18000          NaN     NaN
109   48440497        13.5         NaN         2.00          NaN     -2.64000          NaN     NaN
122   51327011       312.0         NaN         1.65          NaN      1.04000          NaN     NaN
132   53821197       297.0         NaN        -2.45          NaN     -0.77700          NaN     NaN
139   56006835       365.0         NaN        -1.58          NaN      1.44000          NaN     NaN
215   73329166       387.0         NaN         1.83          NaN      2.56000          NaN     NaN
331  103291639       359.0         NaN        -1.40          NaN      0.48400          NaN     NaN
355  107080763       359.0         NaN         2.46          NaN     -0.09370          NaN     NaN
365  108837521       447.0         NaN        -1.57          NaN     -3.06000          NaN     NaN
425  150062352       165.0         NaN        -1.43          NaN      0.49000          NaN     NaN
635  471618091        61.4         NaN        -2.28          NaN     -1.21000          NaN     NaN
690  495970697       566.0         NaN        -1.91          NaN     -0.00262          NaN     NaN
715  536297170       503.0         NaN         1.95          NaN      0.60400          NaN     NaN

In [114]:
## Compare Photon
column_name = 'pho_pt'
column_name2 = 'pho_eta'
column_name3 = 'pho_phi'
column_name4 = 'pho_ID'
different_values = merged_df[merged_df[f'{column_name}_{f1}'] != merged_df[f'{column_name}_{f2}']]
condition_p = different_values[[f'{column_name}_{f1}', f'{column_name}_{f2}']].isna().all(axis=1)
df_pho = different_values[~condition_p]
df_pho[['evtID', f'{column_name}_{f1}', f'{column_name}_{f2}',f'{column_name2}_{f1}',f'{column_name2}_{f2}',f'{column_name3}_{f1}',f'{column_name3}_{f2}',f'{column_name4}']]

         evtID  pho_pt_KIT  pho_pt_KNU  pho_eta_KIT  pho_eta_KNU  pho_phi_KIT  pho_phi_KNU  pho_ID
59    38430353         NaN       330.0          NaN         1.76          NaN     -1.17000     3.0
122   51327011         NaN       309.0          NaN         1.67          NaN      1.03000     3.0
132   53821197         NaN       298.0          NaN        -2.44          NaN     -0.77300     3.0
139   56006835         NaN       368.0          NaN        -1.58          NaN      1.44000     3.0
215   73329166         NaN       386.0          NaN         1.83          NaN      2.56000     1.0
331  103291639         NaN       358.0          NaN        -1.40          NaN      0.47800     3.0
355  107080763         NaN       361.0          NaN         2.45          NaN     -0.08980     3.0
365  108837521         NaN       447.0          NaN        -1.58          NaN     -3.06000     3.0
425  150062352         NaN       165.0          NaN        -1.43          NaN      0.46900     3.0
690  495970697         NaN       564.0          NaN        -1.91          NaN     -0.00388     3.0
715  536297170         NaN       501.0          NaN         1.95          NaN      0.60600     3.0

In [115]:
column_name5 = 'ele_pt'
column_name6 = 'ele_eta'
column_name7 = 'ele_phi'
column_name8 = 'ele_ID'
df_pho[['evtID', 
#        f'{column_name}_{f1}', f'{column_name}_{f2}',
#        f'{column_name2}_{f1}',f'{column_name2}_{f2}',
#        f'{column_name3}_{f1}', f'{column_name3}_{f2}',
        f'{column_name4}',# f'{column_name4}_{f2}',
#        f'{column_name5}_{f1}', f'{column_name5}_{f2}',
#        f'{column_name6}_{f1}', f'{column_name6}_{f2}',
#        f'{column_name7}_{f1}', f'{column_name7}_{f2}',
        f'{column_name8}',# f'{column_name8}_{f2}',
       ]]

         evtID  pho_ID  ele_ID
59    38430353     3.0     NaN
122   51327011     3.0     NaN
132   53821197     3.0     NaN
139   56006835     3.0     NaN
215   73329166     1.0     NaN
331  103291639     3.0     NaN
355  107080763     3.0     NaN
365  108837521     3.0     NaN
425  150062352     3.0     NaN
690  495970697     3.0     NaN
715  536297170     3.0     NaN

In [75]:
## Compare Muon
column_name = 'mu_pt'
column_phi = 'mu_phi'
different_values = merged_df[merged_df[f'{column_name}_{f1}'] != merged_df[f'{column_name}_{f2}']]
condition_p = different_values[[f'{column_name}_{f1}', f'{column_name}_{f2}',f'{column_name}_{f1}',f'{column_name}_{f2}']].isna().all(axis=1)
df_pho = different_values[~condition_p]
df_pho[['evtID', f'{column_name}_{f1}', f'{column_name}_{f2}',f'{column_phi}_{f1}',f'{column_phi}_{f2}']]

Empty DataFrame
Columns: [evtID, mu_pt_KIT, mu_pt_KNU, mu_phi_KIT, mu_phi_KNU]
Index: []

In [68]:
column_name = 'recoil'
def round_to_3_sig_figs(x):
    return round(x, -int(np.floor(np.log10(abs(x)))) + 2)
merged_df[f'recoil_{f1}'] = merged_df[f'recoil_{f1}'].apply(round_to_3_sig_figs)
diff_recoil = merged_df[ abs(merged_df[f'{column_name}_{f1}'] - merged_df[f'{column_name}_{f2}']) > 1]
diff_recoil[['evtID', f'{column_name}_{f1}', f'{column_name}_{f2}']]

         evtID  recoil_KIT  recoil_KNU
7     14166655        65.5        62.6
36    19508071        83.0        80.5
59    38430353       355.0       351.0
109   48440497       410.0       405.0
122   51327011       368.0       365.0
137   55485530       317.0       288.0
139   56006835       344.0       346.0
222   76582893       309.0       305.0
241   79999559       290.0       299.0
259   84383142       341.0       315.0
318  100309022       256.0       254.0
336  103809887       474.0       571.0
338  104312092       296.0       319.0
355  107080763       370.0       372.0
459  175868116       310.0        66.1
505  246088422       307.0       280.0
509  247617927       333.0       504.0
517  252776036       268.0       271.0
553  259892373       310.0       313.0
557  260881318       602.0       600.0
611  306255608       310.0       281.0
635  471618091       230.0       194.0
643  477078534       294.0       288.0
668  490911477       331.0       351.0
683  494962967       255.0       281.0
691  495999951       417.0       283.0
715  536297170       539.0       537.0

In [ ]:
## Reset display options
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')
pd.reset_option('display.width')
pd.reset_option('display.max_colwidth')

## Reset all options
pd.reset_option('all')